services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: wpilib/roborio-cross-ubuntu:2022-20.04
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
